exports.handler = async () => {
    return {
        statusCode: 200,
        body: JSON.stringify([
                {

        id: 29,
        title: "S Line S1- E1",
        description: "Korean Series",
        thumbnail: "assets/sline-1.jpg",
        videoUrl: "https://streamtape.com/e/dZVZG17w93skm77",
        year: 2025,
        genre: "Thriller/Mystery",
        duration: "1H 50M",
        isSlines : true,
        isBseries : false,
        isHot : true,
        isSouth : false,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: false,
        isHorror: false,
        isNew: false,
        isPopular: false,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "series"

          },

               {

        id: 28,
        title: "S Line S1- E2",
        description: "Korean Series",
        thumbnail: "assets/sline-2.jpg",
        videoUrl: "https://streamtape.com/e/mYwg8Mkkppib3AA",
        year: 2025,
        genre: "Thriller/Mystery",
        duration: "1H 50M",
        isSlines : true,
        isBseries : false,
        isHot : false,
        isSouth : false,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: false,
        isHorror: false,
        isNew: false,
        isPopular: false,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "series"

          },
           {

        id: 29,
        title: "S Line S1- E3",
        description: "Korean Series",
        thumbnail: "assets/sline-3.jpg",
        videoUrl: "https://streamtape.com/e/KGkj280pmoc0OgJ",
        year: 2025,
        genre: "Thriller/Mystery",
        duration: "1H 50M",
        isSlines : true,
        isBseries : false,
        isHot : false,
        isSouth : false,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: false,
        isHorror: false,
        isNew: false,
        isPopular: false,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "series"

          },
           {

        id: 30,
        title: "S Line S1- E4",
        description: "Korean Series",
        thumbnail: "assets/sline-4.jpg",
        videoUrl: "https://streamtape.com/e/kzrrmvjVKdSOK24",
        year: 2025,
        genre: "Thriller/Mystery",
        duration: "1H 50M",
        isSlines : true,
        isBseries : false,
        isHot : false,
        isSouth : false,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: false,
        isHorror: false,
        isNew: false,
        isPopular: false,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "series"

          },


            {

        id: 27,
        title: "Virus",
        description: "Bangla Series",
        thumbnail: "assets/virus.png",
        videoUrl: "https://streamtape.com/e/lw1yVLRe8WCzp9",
        year: 2023,
        genre: "Thriller/Mystery",
        duration: "1H 50M",
        isBseries : true,
        isHot : true,
        isSouth : false,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: true,
        isHorror: false,
        isNew: false,
        isPopular: false,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "series"

          },


             {

        id: 26,
        title: "Mission: Impossible : The Final Reckoning",
        description: "English Movie",
        thumbnail: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcShcMw2wUx24KAWkT-eQaC8bCB5EzkApaInrKpXeGm_UM8HcBlN",
        videoUrl: "https://streamtape.com/e/0eeMR4rmKeSbPzl",
        year: 2025,
        genre: "Horror/Mystery",
        duration: "1H 50M",
        isHot : true,
        isSouth : false,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: true,
        isHorror: false,
        isNew: false,
        isPopular: true,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "movie"

          },


            {

        id: 25,
        title: "Final Destination Bloodlines",
        description: "English Movie",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSRY-xDKrIC0cj-mHHeX9A6K3s3fXn4FjsycWtbRBx2Jd3HcuF",
        videoUrl: "https://streamtape.com/e/xOMWxpMOZ6ikrK3",
        year: 2025,
        genre: "Horror/Mystery",
        duration: "1H 50M",
        isHot : true,
        isSouth : false,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: true,
        isHorror: false,
        isNew: false,
        isPopular: true,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "movie"

          },
           
          {
        id: -4,
        title: "Loki S01 - EP01",
        description: "Hindi Movie",
        thumbnail: "assets/loki1.png",
        videoUrl: "https://streamtape.com/e/p28jr4d9wDCraLl",
        year: 2021,
        genre: "Sci-Fi",
        duration: "02h 04m",
        isLoki : true,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: true,
        isHorror: false,
        isNew: false,
        isPopular: true,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "movie"

          },

           {
        id: -5,
        title: "Loki S01 - EP02",
        description: "Hindi Movie",
        thumbnail: "assets/loki2.png",
        videoUrl: "https://streamtape.com/e/RgOQXwJyY9Idw9X",
        year: 2021,
        genre: "Sci-Fi",
        duration: "02h 04m",
        isLoki : true,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: false,
        isHorror: false,
        isNew: false,
        isPopular: true,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "movie"


    },


      {
        id: -6,
        title: "Loki S01 - EP03",
        description: "Hindi Movie",
        thumbnail: "assets/loki3.png",
        videoUrl: "https://streamtape.com/e/2WRPlk1WwouZ02B",
        year: 2021,
        genre: "Sci-Fi",
        duration: "02h 04m",
        isLoki : true,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: false,
        isHorror: false,
        isNew: false,
        isPopular: true,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "movie"


    },
      {
        id: -7,
        title: "Loki S01 - EP04",
        description: "Hindi Movie",
        thumbnail: "assets/loki4.png",
        videoUrl: "https://streamtape.com/e/RkWjR3v7XVhdryV",
        year: 2021,
        genre: "Sci-Fi",
        duration: "02h 04m",
        isLoki : true,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: false,
        isHorror: false,
        isNew: false,
        isPopular: true,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "movie"


    },

              {
        id: -8,
        title: "Loki S01 - EP05",
        description: "Hindi Movie",
        thumbnail: "assets/loki5.png",
        videoUrl: "https://streamtape.com/e/kzJoPGmBdJsY7J",
        year: 2021,
        genre: "Sci-Fi",
        duration: "02h 04m",
        isLoki : true,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: false,
        isHorror: false,
        isNew: false,
        isPopular: true,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "movie"
        


    },

           {
        id: -9,
        title: "Loki S01 - EP06",
        description: "Hindi Movie",
        thumbnail: "assets/loki6.png",
        videoUrl: "https://streamtape.com/e/b3m0QALMlYuPwr4",
        year: 2021,
        genre: "Sci-Fi",
        duration: "02h 04m",
        isLoki : true,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: false,
        isHorror: false,
        isNew: false,
        isPopular: true,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "movie"


    },

 

         

         

          

        {
        id: -3,
        title: "The House Next Door",
        description: "Hindi Movie",
        thumbnail: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRO9yutB99OUfdlxk0ajLcKukIjysIab5LwBeIlukT0Luy-auYS",
        videoUrl: "https://www.youtube.com/embed/KoEQs9VlWUA",
        year: 2017,
        genre: "Horror",
        duration: "02h 04m",
        isHindi: true,
        isDaagi: false,
        isArrived: false,
        isTrending: true,
        isHorror: true,
        isNew: false,
        isPopular: false,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "movie"


    },
            
          {
        id: -2,
        title: "Chokkor 302 (চক্কর)",
        description: "Bangla Movie",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/72/Chokkor_302_official_logo.jpg",
        videoUrl: "https://streamtape.com/e/zXeqgMqROPfYz0y",
        year: 2025,
        genre: "Action/Thriller",
        duration: "02h 04m",
        isHindi: false,
        isDaagi: true,
        isArrived: false,
        isTrending: true,
        isHorror: false,
        isNew: false,
        isPopular: false,
        isAction: true,
        isDrama: false,
        isComedy: false,
        type: "movie"


    },


      {
        id: -1,
        title: "Jawan: Extended Version",
        description: "Bangla Movie",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/3/39/Jawan_film_poster.jpg",
        videoUrl: "https://streamtape.com/e/ea0o0L1GQlhZl2",
        year: 2025,
        genre: "Action/Thriller",
        duration: "02h 04m",
        isHindi: true,
        isDaagi: false,
        isArrived: false,
        isTrending: true,
        isHorror: false,
        isNew: false,
        isPopular: false,
        isAction: true,
        isDrama: false,
        isComedy: false,
        type: "movie"


    },
 


       {
        id: 0,
        title: "Black widow",
        description: "MCU",
        thumbnail: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSBmdUgWZHrTE5bP78kiJiR62ZHXQ4lbLaDCifVZkzezR6K6KhK",
        videoUrl: "https://vide0.net/e/0u5ff0vd5fnu",
        year: 2021,
        genre: "Action",
        duration: "30m",
        isTrending: false,
        isNew: false,
        isPopular: true,
        isAction: true,
        isDrama: false,
        isComedy: false,
        type: "movie"
    },
    {
        id: 1,
        title: "S4 E1 - Case-Mukadma",
        description: "Abhishek fears the police case for slapping Bhushan could ruin his career.",
        thumbnail: "https://m.media-amazon.com/images/S/pv-target-images/fee51dd5d85f43866f91ca4887f03813325c92879c0df1a9ab07a29b26ba5b3e._BR-6_AC_SX360_FMwebp_.jpg",
        videoUrl: "https://vide0.net/e/1tgrur45tda0",
        year: 2025,
        genre: "Drama",
        duration: "30m",
        isTrending: false,
        isNew: true,
        isPopular: true,
        isAction: false,
        isDrama: true,
        isComedy: false,
        type: "tv"
    },
    {
        id: 2,
        title: "S4 E2 - Zakhm",
        description: "Pradhan, a survivor of an assassination attempt, tries to leverage sympathy.",
        thumbnail: "https://m.media-amazon.com/images/S/pv-target-images/658c8ad8fd3e80fc54ce75a94ff4c9f26edbc477ff06338abea073c3f23bc50f._BR-6_AC_SX360_FMwebp_.jpg",
        videoUrl: "https://vide0.net/e/jblmx2705sf3",
        year: 2025,
        genre: "Drama",
        duration: "30m",
        isTrending: false,
        isNew: true,
        isPopular: false,
        isAction: false,
        isDrama: true,
        isComedy: false,
        type: "tv"
    },
    {
        id: 3,
        title: "S4 E3 - Vachan",
        description: "After noticing a crack in Bhushan's camp, Pradhan sees an opportunity.",
        thumbnail: "https://m.media-amazon.com/images/S/pv-target-images/f3ad33eca1558fbfb5dc9b25e53a3bad136b8fd613955bcfa21764d7bf9676e4._BR-6_AC_SX360_FMwebp_.jpg",
        videoUrl: "https://vide0.net/e/wtr88itqbuoq",
        year: 2025,
        genre: "Drama",
        duration: "30m",
        isTrending: false,
        isNew: true,
        isPopular: false,
        isAction: false,
        isDrama: true,
        isComedy: false,
        type: "tv"
    },
    {
        id: 4,
        title: "S4 E4 - Shakti Pradarshan",
        description: "While Pradhan and Manju Devi prepare for a grand nomination.",
        thumbnail: "https://m.media-amazon.com/images/S/pv-target-images/b71dd2cfb7df8b20cabde29463a80195d2c57bbcfc3adb8a725876fdd1e3530b._BR-6_AC_SX360_FMwebp_.jpg",
        videoUrl: "https://vide0.net/e/s6e61pitxbx6",
        year: 2025,
        genre: "Drama",
        duration: "30m",
        isTrending: false,
        isNew: true,
        isPopular: false,
        isAction: false,
        isDrama: true,
        isComedy: false,
        type: "tv"
    },
    {
        id: 5,
        title: "S4 E5 - Ashirvaad",
        description: "A few days before the election, Manju Devi's father visits Phulera.",
        thumbnail: "https://m.media-amazon.com/images/S/pv-target-images/91611c3de909d8a6ab93923a44b38f9a89b8b5534ccece9855c0db8e6ed829c8._BR-6_AC_SX360_FMwebp_.jpg",
        videoUrl: "https://vide0.net/e/3ez5zvd3b9m3",
        year: 2025,
        genre: "Drama",
        duration: "30m",
        isTrending: false,
        isNew: true,
        isPopular: false,
        isAction: false,
        isDrama: true,
        isComedy: false,
        type: "tv"
    },
    {
        id: 6,
        title: "S4 E6 - Sanjeevani",
        description: "Jealous of Bhushan gaining strong support in the village.",
        thumbnail: "https://m.media-amazon.com/images/S/pv-target-images/9adacd66ad40d7c3b4f59b2ac1d9592087b33f1cf816b213566c5b3222963650._BR-6_AC_SX360_FMwebp_.jpg",
        videoUrl:  "https://vide0.net/e/9ao73olm5au9",
        year: 2025,
        genre: "Drama",
        duration: "30m",
        isTrending: false,
        isNew: true,
        isPopular: false,
        isAction: false,
        isDrama: true,
        isComedy: false,
        type: "tv"
    },
    {
        id: 7,
        title: "S4 E7 - Dramabaaz",
        description: "Just before election day, the local electricity transformer malfunctions.",
        thumbnail: "https://m.media-amazon.com/images/S/pv-target-images/70a944f8965ab72ff820c9f593aae22ea5dcd4cad340697973c39585baec4930._BR-6_AC_SX360_FMwebp_.jpg",
        videoUrl: "https://vide0.net/e/25sr6c8px0jb",
        year: 2025,
        genre: "Drama",
        duration: "30m",
        isTrending: false,
        isNew: true,
        isPopular: false,
        isAction: false,
        isDrama: true,
        isComedy: false,
        type: "tv"
    },
    {
        id: 8,
        title: "S4 E8 - dabdaba",
        description: "As Abhishek plans his next move after receiving his CAT results.",
        thumbnail: "https://m.media-amazon.com/images/S/pv-target-images/98563df024bb2bd5550b97adc3edf553de28107a440297891d98c3435c1beab3._BR-6_AC_SX360_FMwebp_.jpg",
        videoUrl: "https://vide0.net/e/dl5qq7nthdel",
        year: 2025,
        genre: "Drama",
        duration: "30m",
        isTrending: false,
        isNew: true,
        isPopular: false,
        isAction: false,
        isDrama: true,
        isComedy: false,
        type: "tv"
    },
    {
        id: 9,
        title: "Avengers : DoomsDay",
        description: "A group of vigilantes set out to take down corrupt superheroes.",
        thumbnail: "https://i.ytimg.com/vi/XLuL_TXbK1g/hqdefault.jpg",
        videoUrl: "https://vide0.net/e/psxj0le5qcxi",
        year: 2026,
        genre: "Action",
        duration: "1h",
        isTrending: false,
        isNew: false,
        isPopular: true,
        isAction: true,
        isDrama: false,
        isComedy: false,
        type: "movie"
    },
    {
        id: 10,
        title: "Utshob",
        description: "Bangla Movie",
        thumbnail: "https://i.ytimg.com/vi/jHPf1iKw4T8/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/jHPf1iKw4T8",
        year: 2025,
        genre: "Drama/Comedy",
        duration: "50m",
        isTrending: true,
        isNew: false,
        isPopular: true,
        isAction: false,
        isDrama: true,
        isComedy: true,
        type: "movie"
    },
    {
        id: 11,
        title: "Taandob",
        description: "Bangla Movie",
        thumbnail: "https://m.media-amazon.com/images/M/MV5BZmMwZTk1MDctMjM1My00YTA5LTg0YmYtZWE5Y2Q4N2JhZGQ1XkEyXkFqcGc@._V1_FMjpg_UX1080_.jpg",
        videoUrl: "https://vide0.net/e/1980xgp9v70x",
        year: 2025,
        genre: "Action",
        duration: "2h 09m",
        isTrending: true,
        isNew: false,
        isPopular: true,
        isAction: true,
        isDrama: false,
        isComedy: false,
        type: "movie"
    },
    {
        id: 12,
        title: "ThunderBolt*",
        description: "Sam online",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUWr47D8jZJ_7_U298o1wURdsW6-m43EYG8nWQeEObCLbyztkc",
        videoUrl: "https://moon-spacex.web.app/thunderbolt.html",
        year: 2025,
        genre: "Drama",
        duration: "30m",
        isTrending: true,
        isNew: false,
        isPopular: true,
        isAction: true,
        isDrama: false,
        isComedy: true,
        type: "special"
    },
    {
        id: 13,
        title: "S3 E1 Keys and Knives",
        description: "Korean series",
        thumbnail: "https://i.ytimg.com/vi/11Jh0_82fgw/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCPyKRkX-phXKp6-nXER9DA9CNixA",
        videoUrl: "https://streamtape.com/e/4v9pl8xaK6FK6OZ/Squid_Game_S03E01_1080p_NF_WEB-DL_x265_HEVC_MSubs_%5BMulti_Audio%5D%5BHindi_5.1%2BEnglish_5.1%2BKorean_5.1%5D_-KmHD.mp4",
        year: 2025,
        genre: "Action/Thriller",
        duration: "40m",
        isArrived: true,
        isTrending: false,
        isNew: false,
        isPopular: false,
        isAction: true,
        isDrama: false,
        isComedy: false,
        type: "tv"
    },
    {
        id: 14,
        title: "S3 E2 The Starry Night ",
        description: "Korean series",
        thumbnail: "assets/2.jpg",
        videoUrl: "https://streamtape.com/e/agYzmrzOBPixrox",
        year: 2025,
        genre: "Action/Thriller",
        duration: "40m",
        isArrived: true,
        isTrending: false,
        isNew: false,
        isPopular: false,
        isAction: true,
        isDrama: false,
        isComedy: false,
        type: "tv"
    },
    {
        id: 15,
        title: "S3 E3  It's Not Your Fault",
        description: "Korean Series",
        thumbnail: "assets/3.jpg",
        videoUrl: "https://streamtape.com/e/Rm2dxGgVv6CdgpB/Squid_Game_S03E03_1080p_NF_WEB-DL_x265_HEVC_MSubs_%5BMulti_Audio%5D%5BHindi_5.1%2BEnglish_5.1%2BKorean_5.1%5D_-KmHD.mp4",
        year: 2025,
        genre: "Action/Thriller",
        duration: "40m",
        isArrived: true,
        isTrending: false,
        isNew: false,
        isPopular: false,
        isAction: true,
        isDrama: false,
        isComedy: false,
        type: "tv"
    },
    {
        id: 16,
        title: "S3  E4  '222'",
        description: "Korean Series",
        thumbnail: "assets/4.jpg",
        videoUrl: "https://streamtape.com/e/MqeXWZMrXZumag3/Squid_Game_S03E04_1080p_NF_WEB-DL_x265_HEVC_MSubs_%5BMulti_Audio%5D%5BHindi_5.1%2BEnglish_5.1%2BKorean_5.1%5D_-KmHD.mp4",
        year: 2025,
        genre: "Action/Thriller",
        duration: "40m",
        isArrived: true,
        isTrending: false,
        isNew: false,
        isPopular: false,
        isAction: true,
        isDrama: false,
        isComedy: false,
        type: "tv"
    },
    {
        id: 17,
        title: "S3 E5  ○△□",
        description: "Korean Series",
        thumbnail: "assets/5.jpg",
        videoUrl: "https://streamtape.com/e/XB3k8PlZ4eFDJla/Squid_Game_S03E05_1080p_NF_WEB-DL_x265_HEVC_MSubs_%5BMulti_Audio%5D%5BHindi_5.1%2BEnglish_5.1%2BKorean_5.1%5D_-KmHD.mp4",
        year: 2025,
        genre: "Action/Thriller",
        duration: "40m",
        isArrived: true,
        isTrending: false,
        isNew: false,
        isPopular: false,
        isAction: true,
        isDrama: false,
        isComedy: false,
        type: "tv"
    },
    {
        id: 18,
        title: "S3  E6  Humans Are...",
        description: "Korean Series",
        thumbnail: "assets/6.jpg",
        videoUrl: "https://streamtape.com/e/zKdGDz6V86seZo/Squid_Game_S03E06_1080p_NF_WEB-DL_x265_HEVC_MSubs_%5BMulti_Audio%5D%5BHindi_5.1%2BEnglish_5.1%2BKorean_5.1%5D_-KmHD.mp4",
        year: 2025,
        genre: "Action/Thriller",
        duration: "40m",
        isArrived: true,
        isTrending: false,
        isNew: false,
        isPopular: false,
        isAction: true,
        isDrama: false,
        isComedy: false,
        type: "tv"
    },
    {
        id: 19,
        title: "Maa(HDTS)",
        description: "Indian Movie",
        thumbnail: "https://static.moviecrow.com/marquee/kajols-mythological-horror-film-maa-to-release-on-june-27-2025/247113_thumb_665.jpg",
        videoUrl: "https://streamtape.com/e/01Kzj6gz8zhgJy",
        year: 2025,
        genre: "Horror",
        duration: "02h 04m",
        isArrived: false,
        isTrending: false,
        isHorror: true,
        isNew: false,
        isPopular: false,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "movie"
    },
     {
        id: 20,
        title: "DAAGI -দাগি",
        description: "Bangla Movie",
        thumbnail: "https://image-chorki.gotipath.com/uploads/images/2025/06/05/posters_819d5cec8a66473df474b876c45b094f_goplay_800_1200.jpg",
        videoUrl: "https://streamtape.com/e/Le9XBXjrWqURRze",
        year: 2025,
        genre: "Action/Thriller",
        duration: "02h 04m",
        isDaagi: true,
        isArrived: false,
        isTrending: false,
        isHorror: false,
        isNew: false,
        isPopular: false,
        isAction: true,
        isDrama: false,
        isComedy: false,
        type: "movie"
    },


      {
        id: 21,
        title: "Loki S02 - EP01",
        description: "Hindi Movie",
        thumbnail: "assets/loki7.png",
        videoUrl: "https://streamtape.com/e/V8Qq2gXG0VcKMA4",
        year: 2023,
        genre: "Sci-Fi",
        duration: "02h 04m",
        isLokitwo : true,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: true,
        isHorror: false,
        isNew: false,
        isPopular: true,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "series"

          },

          {

        id: 22,
        title: "Loki S02 - EP02",
        description: "Hindi Movie",
        thumbnail: "assets/loki8.png",
        videoUrl: "https://streamtape.com/e/4qBOwwjYaVIKXR1",
        year: 2023,
        genre: "Sci-Fi",
        duration: "02h 04m",
        isLokitwo : true,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: true,
        isHorror: false,
        isNew: false,
        isPopular: true,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "movie"

          },


        {

        id: 23,
        title: "Loki S02 - EP03",
        description: "Hindi Movie",
        thumbnail: "assets/loki9.png",
        videoUrl: "https://streamtape.com/e/782YzgQaBWTAA20",
        year: 2023,
        genre: "Sci-Fi",
        duration: "02h 04m",
        isLokitwo : true,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: true,
        isHorror: false,
        isNew: false,
        isPopular: true,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "movie"

          },
         {

        id: 24,
        title: "Loki S02 - EP04",
        description: "Hindi Movie",
        thumbnail: "assets/loki10.png",
        videoUrl: "https://streamtape.com/e/eALdra26oMI23g",
        year: 2023,
        genre: "Sci-Fi",
        duration: "02h 04m",
        isLokitwo : true,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: true,
        isHorror: false,
        isNew: false,
        isPopular: true,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "movie"

          },

           {

        id: 25,
        title: "Loki S02 - EP05",
        description: "Hindi Movie",
        thumbnail: "assets/loki11.png",
        videoUrl: "https://streamtape.com/e/RjovZAG6oPiXQ6",
        year: 2023,
        genre: "Sci-Fi",
        duration: "02h 04m",
        isLokitwo : true,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: true,
        isHorror: false,
        isNew: false,
        isPopular: true,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "movie"

          },

          {

        id: 26,
        title: "Loki S02 - EP06",
        description: "Hindi Movie",
        thumbnail: "assets/loki12.png",
        videoUrl: "https://streamtape.com/e/wlKRWe6ebbFJ3xo",
        year: 2023,
        genre: "Sci-Fi",
        duration: "02h 04m",
        isLokitwo : true,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: true,
        isHorror: false,
        isNew: false,
        isPopular: true,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "movie"

          },

           {

        id: 27,
        title: "Hridayam",
        description: "South Movie",
        thumbnail: "https://img1.hotstarext.com/image/upload/f_auto/sources/r1/cms/prod/6587/1366587-i-f725eac0c939",
        videoUrl: "https://www.youtube.com/embed/uTiMHpFpF_g",
        year: 2022,
        genre: "Drama/Romance",
        duration: "02h 04m",
        isSouth : true,
        isHindi: false,
        isDaagi: false,
        isArrived: false,
        isTrending: true,
        isHorror: false,
        isNew: false,
        isPopular: true,
        isAction: false,
        isDrama: false,
        isComedy: false,
        type: "movie"

          },
          
        ])
    };
};